---
title: "Give it a title"
author: 
  - "Sara Armstrong"
  - "Grace Fain"
  - "Sifan Tao"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

##Aces are more common on grass surface
```{r, echo=F, cache=T}
library(tidyverse)
library(gt)
library(ggdendro)
library(seriation)
library(flexclust)
library(protoclust)
wta_2018_2021_matches <-
  map_dfr(c(2018:2021),
          function(year) {
            read_csv(paste0("https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_matches_",
                            year, ".csv")) %>%
              mutate(winner_seed = as.character(winner_seed),
                     loser_seed = as.character(loser_seed))
          })
wta = wta_2018_2021_matches

wta %>% 
  mutate(total_ace = w_ace+l_ace) %>% 
  filter(total_ace <50) %>%
  ggplot(aes(y=total_ace, fill=surface)) +
  geom_boxplot(aes(x='')) +
  coord_flip() + 
  theme_bw() + 
  scale_fill_manual(values = c("Grass" = "Green", "Clay" = 'OrangeRed', "Hard" = "SkyBlue")) +
  xlab("Surface type") +
  ylab("Number of aces from both players")
```

---

##Match length is longer in later rounds
```{r, echo=F}
wta$round=as.factor(wta$round)
wta$round = fct_relevel(wta$round, 
            c("F", "SF", "QF", "R16", 
              "R32", "R64", "R128", "RR"))

wta %>%
  filter(minutes<300) %>%
  ggplot(aes(x=minutes)) + 
  geom_density() +
  facet_wrap(~ round) +
  geom_rug(alpha=0.3) + 
  theme_bw() + 
  xlab("Match Length in Minutes") +
  ylab("Distribution of Match Length")
```

---

##Players perform better on certain surfaces
```{r, echo=F}
games_win = wta %>% 
  group_by(winner_name, surface) %>%
  count() %>%
  rename(player = winner_name)

games_lose = wta %>%
  group_by(loser_name, surface) %>%
  count() %>%
  rename(player = loser_name)

full_join(games_lose, games_win, by=c('player', 'surface')) %>%
  rename(wins = "n.y", losses = "n.x") %>% 
  replace_na(list(losses = 0, wins=0)) %>%
  mutate(total = wins+losses, winrate = wins/total) %>%
  arrange(surface, desc(winrate)) %>%
  filter(total >= 10) %>% 
  ungroup() %>%
  group_by(surface) %>%
  slice(1:5) %>%
  mutate(surface = as.factor(surface), 
         player=reorder_within(player, -winrate, surface)) %>%
  ggplot(aes(x=player, y=winrate, fill=surface)) +
  geom_bar(stat='identity', width = 0.5) + 
  facet_wrap(~surface, ncol=3, scales = "free_x") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  xlab("Player Name") +
  ylab("Player Winrate") +
  scale_fill_manual(values = c("Grass" = "Green", "Clay" = 'OrangeRed', "Hard" = "SkyBlue")) +
  scale_x_reordered()


```

---
##Players have different strategies on serving
```{r, echo=F, fig.asp=1, fig.width=3.5,out.width="50%",  fig.align='center'}
winner_ace_df = wta %>%
  group_by(winner_name) %>%
  summarise(total_ace_win = sum(w_ace, na.rm = T),
            total_df_win = sum(w_df, na.rm = T),
            n_game_win = n()) %>%
  rename(name=winner_name)

loser_ace_df = wta %>%
  group_by(loser_name) %>%
  summarise(total_ace_lose = sum(l_ace, na.rm = T),
            total_df_lose = sum(l_df, na.rm = T),
            n_game_lose = n()) %>%
  rename(name=loser_name)

all_ace_df = full_join(winner_ace_df, loser_ace_df, by='name') %>%
  replace_na(list(total_ace_win = 0, total_df_win = 0, n_game_win = 0,
                  total_ace_lose = 0, total_df_lose = 0, n_game_lose = 0)) %>%
  mutate(avg_ace = (total_ace_win+total_ace_lose)/(n_game_win+n_game_lose),
         avg_df = (total_df_win+total_df_lose)/(n_game_win+n_game_lose)) %>%
  filter(n_game_win+n_game_lose>10)

player_dist = dist(select(all_ace_df, avg_ace, avg_df))

wta_minimax = protoclust(player_dist)

all_ace_df %>% 
  mutate(player_clusters = as.factor(protocut(wta_minimax, k=3)$cl)) %>%
  ggplot(aes(x=avg_ace, y=avg_df, color=player_clusters)) + 
  geom_point(alpha=0.7) + 
  theme_bw() +
  theme(legend.position = "bottom") +
  ggthemes::scale_color_colorblind() +
  xlab("Average Aces of a Player") +
  ylab("Average Double Faults of a Player") +
  labs(color="Player Clusters")

```


